### ISSUE TITLE
Release 1.1.0 to PyPI?

### ISSUE THREAD

**Issue by mgedmin** [zzzsochi/beaker_redis#3]
Would you mind cutting a new release to PyPI?  There's a [commit from 2016]( 9c216e5c1614c6c34076a1e06f905ac0c73c2261) that I would find very helpful.

I would be happy to help in any way I can.

**Comment by zzzsochi** [comment]
Done.   :-)

**Comment by mgedmin** [comment]
:heart: Thank you!
